CREATE TABLE IF NOT EXISTS bingo_state (
  id TEXT PRIMARY KEY,
  data TEXT NOT NULL CHECK (length(data) <= 4096),
  version INTEGER NOT NULL DEFAULT 1,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
